version: '3'
services:
  chatbot:
    image: 7940image
    # missing instructions for setting environment variable
    # missing instructions for setting the entrypoint and/or command

  #  HOST=redis
  #  PASSWORD=comp7940passwordlab8
  #  REDISPORT=6379

    depends_on:
      - redis
  redis:
    image: redis
    volumes:
       - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: ["/usr/local/etc/redis/redis.conf"]